{
 "title": "Fibertel",
 "tags": [
  "Internet",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Upstream channel status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fibertel_upstream_locked_bool", "legendFormat": "Channel {{channel_id_up}}" },
    {
     "expr": "fibertel_ofdm_upstream_locked_bool",
     "legendFormat": "Channel {{channel_id_ofdm}} (OFDM)"
    }
   ]
  },
  {
   "title": "Upstream power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    { "expr": "fibertel_upstream_power_dBmV", "legendFormat": "Channel {{channel_id_up}}" },
    {
     "expr": "fibertel_ofdm_upstream_power_dBmV",
     "legendFormat": "Channel {{channel_id_ofdm}} (OFDM)"
    }
   ]
  },
  {
   "title": "Downstream channel status",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fibertel_downstream_locked_bool",
     "legendFormat": "Channel {{channel_id}}"
    },
    {
     "expr": "fibertel_ofdm_downstream_locked_bool",
     "legendFormat": "Channel {{channel_id_ofdm}} (OFDM)"
    }
   ]
  },
  {
   "title": "Downstream power",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    { "expr": "fibertel_downstream_power_dBmV", "legendFormat": "Channel {{channel_id}}" },
    {
     "expr": "fibertel_ofdm_downstream_power_dBmV",
     "legendFormat": "Channel {{channel_id_ofdm}} (OFDM)"
    }
   ]
  },
  {
   "title": "Downstream SNR",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    { "expr": "fibertel_downstream_snr_dB", "legendFormat": "Channel {{channel_id}}" },
    {
     "expr": "fibertel_ofdm_downstream_snr_dB",
     "legendFormat": "Channel {{channel_id_ofdm}} (OFDM)"
    }
   ]
  }
 ]
}